# Spring
server:
  port: 8888
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    #url: jdbc:h2:file:./target/local_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: postgres
    password: postgres
  h2.console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      charSet: UTF-8
      characterEncoding: UTF-8
      useUnicode: true
      hibernate:
        enable_lazy_load_no_trans: true
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strateg: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        ddl-auto: create-drop
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
hibernate:
  enable_lazy_load_no_trans: true